### ISSUE TITLE
`Marshal()` includes `"default="` tags in `EnvSet` output

### ISSUE THREAD

**Issue by fg-j** [Netflix/go-env#23]
I'm interested in using `env.Marshal()` to facilitate logging the environment variables that are set in build configuration for several [Paketo Buildpacks](https://github.com/orgs/paketo-buildpacks/repositories).

We'd like to use the `default=` tag on some of our configuration struct fields. But when I iterate over the output of `env.Marshal(&myStruct)` to log the values of the environment variables, I see that the tags `default=*` are included as keys in the EnvSet. 

See this [Go playground](https://go.dev/play/p/5uoiwmQqgTU) for an example of what I mean.

**Comment by hinshun** [comment]
@jimmykodes can you help with this?
